name: Sync to Theme Repository

on:
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的提交历史
        
    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Clean posts directory and remove workflow files
      run: |
        # 进入posts目录
        cd src/content/posts
        
        # 删除除了markdown.md以外的所有文件
        find . -type f -name "*.md" ! -name "markdown.md" -delete
        
        # 显示剩余文件
        echo "Remaining files in posts directory:"
        ls -la
        
        # 返回项目根目录
        cd ../../..
        
        # 删除所有工作流文件
        if [ -d ".github" ]; then
          echo "Removing .github directory..."
          rm -rf .github
          echo "✅ .github directory removed"
        else
          echo "No .github directory found"
        fi
        
    - name: Commit changes if any
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Clean posts directory and remove workflows for theme sync"
        fi
        
    - name: Setup SSH and push to target repository
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # 检查是否设置了SSH_PRIVATE_KEY
        if [ -z "$SSH_PRIVATE_KEY" ]; then
          echo "❌ SSH_PRIVATE_KEY secret not found!"
          echo "Please add your SSH private key as SSH_PRIVATE_KEY secret"
          echo "Generate SSH key: ssh-keygen -t rsa -b 4096 -C 'your_email@example.com'"
          echo "Add public key to GitHub: https://github.com/settings/keys"
          exit 1
        fi
        
        # 设置SSH密钥
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # 添加GitHub到known_hosts
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
        # 测试SSH连接
        echo "🔍 Testing SSH connection to GitHub..."
        ssh -T git@github.com || echo "SSH connection test completed"
        
        # 添加远程仓库（使用SSH）
        git remote add theme-repo git@github.com:fishcpy/astro-theme-fishcpy.git
        
        # 推送到目标仓库
        echo "🚀 Pushing to target repository..."
        git push theme-repo main --force-with-lease
        
    - name: Summary
      run: |
        echo "✅ Successfully synced to theme repository"
        echo "🗑️  Cleaned posts directory (kept only markdown.md)"
        echo "🗑️  Removed all workflow files (.github directory)"
        echo "📝 Updated banner.enable to true"
        echo "🔄 Pushed with commit history to git@github.com:fishcpy/astro-theme-fishcpy.git"
        echo ""
        echo "📋 Setup Instructions (if this was your first run):"
        echo "1. Generate SSH key: ssh-keygen -t rsa -b 4096 -C 'your_email@example.com'"
        echo "2. Add public key to GitHub: https://github.com/settings/keys"
        echo "3. Add private key as SSH_PRIVATE_KEY secret in repository settings"
        echo "4. Ensure target repository exists: https://github.com/fishcpy/astro-theme-fishcpy"