name: Sync to Theme Repository

on:
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的提交历史
        
    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Clean posts directory (keep only markdown.md)
      run: |
        # 进入posts目录
        cd src/content/posts
        
        # 删除除了markdown.md以外的所有文件
        find . -type f -name "*.md" ! -name "markdown.md" -delete
        
        # 显示剩余文件
        echo "Remaining files in posts directory:"
        ls -la
        
    - name: Commit changes if any
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Clean posts directory for theme sync"
        fi
        
    - name: Add target repository as remote
      run: |
        git remote add theme-repo https://github.com/fishcpy/astro-theme-fishcpy.git
        
    - name: Push to target repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 使用token进行认证推送
        git remote set-url theme-repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/fishcpy/astro-theme-fishcpy.git
        
        # 推送到目标仓库的main分支
        git push theme-repo main --force-with-lease
        
    - name: Summary
      run: |
        echo "✅ Successfully synced to theme repository"
        echo "🗑️  Cleaned posts directory (kept only markdown.md)"
        echo "📝 Updated banner.enable to true"
        echo "🔄 Pushed with commit history to https://github.com/fishcpy/astro-theme-fishcpy.git"